-- Drop table if exists
DROP TABLE IF EXISTS products;

-- Create table
CREATE TABLE products (
  id INTEGER PRIMARY KEY,
  name TEXT,
  source TEXT,
  bullets_html TEXT,
  bullets_text TEXT,
  features_html TEXT,
  features_text TEXT,
  short_desc_html TEXT,
  short_desc_text TEXT,
  long_desc_html TEXT,
  long_desc_text TEXT
);

-- Inserts

INSERT INTO products (id, name, source, bullets_html, bullets_text, features_html, features_text, short_desc_html, short_desc_text, long_desc_html, long_desc_text) VALUES
(1,
 '702 Black Open FlatTop Plastic Base Cage',
 'aecageco.com',
 '<ul><li>Spacious 22″ × 18″ × 62″ powder‑coated steel cage with a slide‑out tray for easy cleaning</li><li>Top converts into “play area” with full access via opening top</li><li>Dual feeder doors with two plastic cups and perches, plus a sliding front fold‑down door</li><li>Built-in bottom shelf with detached stand on four casters for mobility</li><li>Safe construction: 3/5″ bar spacing, 3 mm wire gauge, non‑toxic powder coat finish</li></ul>',
 '• Spacious 22″ × 18″ × 62″ powder‑coated steel cage with a slide‑out tray for easy cleaning\n• Top converts into “play area” with full access via opening top\n• Dual feeder doors with two plastic cups and perches, plus a sliding front fold‑down door\n• Built-in bottom shelf with detached stand on four casters for mobility\n• Safe construction: 3/5″ bar spacing, 3 mm wire gauge, non‑toxic powder coat finish',
 '<ul><li>Exterior / interior dimensions and structure (22″ × 18″ × 62″; 27″ interior height)</li><li>Bar spacing 3/5″ & 3 mm wire gauge</li><li>Hybrid bar layout: horizontal on sides, vertical on front/back</li><li>Front door with safety latch</li><li>Two feeder doors, two cups & perches</li><li>Sliding front door folds down for front perch access</li><li>Top cage opens fully to act as play top</li><li>Slide‑out bottom tray and removable grill</li><li>Bottom shelf for storing supplies</li><li>Detachable stand with 4 caster wheels</li><li>Durable, non‑toxic powder coated finish</li></ul>',
 '• Exterior / interior dimensions and structure (22″ × 18″ × 62″; 27″ interior height)\n• Bar spacing 3/5″ & 3 mm wire gauge\n• Hybrid bar layout: horizontal on sides, vertical on front/back\n• Front door with safety latch\n• Two feeder doors, two cups & perches\n• Sliding front door folds down for front perch access\n• Top cage opens fully to act as play top\n• Slide‑out bottom tray and removable grill\n• Bottom shelf for storing supplies\n• Detachable stand with 4 caster wheels\n• Durable, non‑toxic powder coated finish',
 'The <strong>702 Black Open FlatTop Cage</strong> is a tall, versatile bird cage featuring a convertible play top, side and front access, easy‑clean tray, bottom storage shelf, and a mobile stand — ideal for medium parrots like cockatiels, conures, lories, or lovebirds.',
 'The 702 Black Open FlatTop Cage is a tall, versatile bird cage featuring a convertible play top, side and front access, easy‑clean tray, bottom storage shelf, and a mobile stand — ideal for medium parrots like cockatiels, conures, lories, or lovebirds.',
 '<p>Constructed with a powder‑coated steel frame and safe 3/5″ bar spacing, the <strong>702 Black Open FlatTop Cage</strong> combines both functionality and style. With exterior dimensions of 22″ × 18″ × 62″ (interior height 27″), it’s generous enough to allow movement without taking over your space. The top flips open to serve as a play area, while the sliding front door folds down for convenient front‑facing access and perching. Dual feeder doors include two plastic feeder cups and perches, and the sliding tray with removable grill keeps cleaning quick and effortless. A bottom shelf provides extra storage for toys, food, or supplies. The cage sits on a detachable stand equipped with four rolling casters for easy repositioning. Finished with a safe, non‑toxic powder coating, this cage is ideal for small to medium parrots such as cockatiels, lories, conures, and lovebirds looking for a durable, functional, and attractive living and play habitat.</p>',
 'Constructed with a powder‑coated steel frame and safe 3/5″ bar spacing, the 702 Black Open FlatTop Cage combines both functionality and style. With exterior dimensions of 22″ × 18″ × 62″ (interior height 27″), it’s generous enough to allow movement without taking over your space. The top flips open to serve as a play area, while the sliding front door folds down for convenient front‑facing access and perching. Dual feeder doors include two plastic feeder cups and perches, and the sliding tray with removable grill keeps cleaning quick and effortless. A bottom shelf provides extra storage for toys, food, or supplies. The cage sits on a detachable stand equipped with four rolling casters for easy repositioning. Finished with a safe, non‑toxic powder coating, this cage is ideal for small to medium parrots such as cockatiels, lories, conures, and lovebirds looking for a durable, functional, and attractive living and play habitat.'
),
(2,
 'HQ Platinum 24×22 Play Top Cage (5/8″ Bar Spacing)',
 'aecageco.com',
 '<ul><li>Spacious 22″ × 24″ × 62″ wrought iron cage with 5/8″ bar spacing and 3.5 mm bar thickness</li><li>Large front door with safety latch, plus three swing‑down feeder doors with stainless steel cups</li><li>Convertible play top featuring 2 ladders, 2 perches, and 2 stainless feeding cups</li><li>Removable seed catcher, slide‑out tray & grill for easy cleanup</li><li>Mounted on 4 rolling casters for mobility, with horizontal/vertical bar layout for structural strength</li></ul>',
 '• Spacious 22″ × 24″ × 62″ wrought iron cage with 5/8″ bar spacing and 3.5 mm bar thickness\n• Large front door with safety latch, plus three swing‑down feeder doors with stainless steel cups\n• Convertible play top featuring 2 ladders, 2 perches, and 2 stainless feeding cups\n• Removable seed catcher, slide‑out tray & grill for easy cleanup\n• Mounted on 4 rolling casters for mobility, with horizontal/vertical bar layout for structural strength',
 '<ul><li>Exterior & interior dimensions (22″ × 24″ × 62″; 30″ interior height)</li><li>Bar spacing: 5/8″; bar thickness: 3.5 mm</li><li>Material: wrought iron with non‑toxic powder coating</li><li>Front door with safety latch (bird‑proof design)</li><li>Three swing‑down feeder doors with stainless steel cups</li><li>Interior wood perch</li><li>Play top with two wood perches, two ladders, two stainless steel feed cups</li><li>Hybrid bar layout: horizontal & vertical bars</li><li>Removable seed catcher</li><li>Slide‑out tray + removable grill</li><li>Four caster wheels for mobility</li></ul>',
 '• Exterior & interior dimensions (22″ × 24″ × 62″; 30″ interior height)\n• Bar spacing: 5/8″; bar thickness: 3.5 mm\n• Material: wrought iron with non‑toxic powder coating\n• Front door with safety latch (bird‑proof design)\n• Three swing‑down feeder doors with stainless steel cups\n• Interior wood perch\n• Play top with two wood perches, two ladders, two stainless steel feed cups\n• Hybrid bar layout: horizontal & vertical bars\n• Removable seed catcher\n• Slide‑out tray + removable grill\n• Four caster wheels for mobility',
 'The <strong>HQ Platinum 24″×22″ Play Top Cage</strong> combines robust construction, user‑friendly features, and a convertible top play area—ideal for medium birds like conures, cockatiels, caiques, and lovebirds.',
 'The HQ Platinum 24″×22″ Play Top Cage combines robust construction, user‑friendly features, and a convertible top play area—ideal for medium birds like conures, cockatiels, caiques, and lovebirds.',
 '<p>Built with wrought iron and a non‑toxic powder‑coated finish, the <strong>HQ Platinum 24″×22″ Play Top Cage</strong> offers both durability and safety. With exterior dimensions of 22″ × 24″ × 62″ and an interior height of 30″, it provides ample space for active birds. Bar spacing is 5/8″ with a solid 3.5 mm bar thickness to prevent escape and enhance strength.</p><p>The cage features a large, bird‑proof front door with safety latch, plus three swing‑down feeder doors equipped with stainless steel cups for easy access. Inside, an interior wood perch provides comfort, while the top converts into a play area with two ladders, two perches, and matching stainless steel feeding cups. A removable seed catcher, slide‑out tray, and grill make cleaning simple and mess‑free. Mounted on four smooth-rolling casters, the cage is easy to move without lifting. Its hybrid bar design offers both structural strength and visual openness. Recommended for conures, cockatiels, caiques, lovebirds, and similar medium-sized birds, this cage strikes a balance between form, function, and aesthetics.</p>',
 'Built with wrought iron and a non‑toxic powder‑coated finish, the HQ Platinum 24″×22″ Play Top Cage offers both durability and safety. With exterior dimensions of 22″ × 24″ × 62″ and an interior height of 30″, it provides ample space for active birds. Bar spacing is 5/8″ with a solid 3.5 mm bar thickness to prevent escape and enhance strength.  The cage features a large, bird‑proof front door with safety latch, plus three swing‑down feeder doors equipped with stainless steel cups for easy access. Inside, an interior wood perch provides comfort, while the top converts into a play area with two ladders, two perches, and matching stainless steel feeding cups. A removable seed catcher, slide‑out tray, and grill make cleaning simple and mess‑free. Mounted on four smooth‑rolling casters, the cage is easy to move without lifting. Its hybrid bar design offers both structural strength and visual openness. Recommended for conures, cockatiels, caiques, lovebirds, and similar medium-sized birds, this cage strikes a balance between form, function, and aesthetics.'
),
(3,
 'HB01406 Small Parrot Pencil',
 'aecageco.com',
 '<ul><li>Natural wood “pencil” chew toy, sized 10″ × 1″, ideal for small parrots</li><li>Lightweight (0.6 lb) design allows easy hanging and movement</li><li>Promotes beak exercise and mental stimulation</li><li>Safe for small species — finches, canaries, parakeets, lovebirds</li><li>Simple, durable design for easy placement in cages</li></ul>',
 '• Natural wood “pencil” chew toy, sized 10″ × 1″, ideal for small parrots\n• Lightweight (0.6 lb) design allows easy hanging and movement\n• Promotes beak exercise and mental stimulation\n• Safe for small species — finches, canaries, parakeets, lovebirds\n• Simple, durable design for easy placement in cages',
 '<ul><li>Dimensions: 10″ × 1″</li><li>Weight: 0.6 lb</li><li>Material: natural wood (safe for birds)</li><li>Hanging hardware: (assumed stainless steel chain or link)</li><li>Intended for chewing, climbing, and talon use</li><li>Enhances enrichment, reduces boredom</li><li>Safe for small bird species (finches, canaries, parakeets, lovebirds)</li></ul>',
 '• Dimensions: 10″ × 1″\n• Weight: 0.6 lb\n• Material: natural wood (safe for birds)\n• Hanging hardware: (assumed stainless steel chain or link)\n• Intended for chewing, climbing, and talon use\n• Enhances enrichment, reduces boredom\n• Safe for small bird species (finches, canaries, parakeets, lovebirds)',
 'A natural wood chew “pencil” designed for small parrots like finches, canaries, parakeets, and lovebirds — perfect for beak exercise and enrichment.',
 'A natural wood chew “pencil” designed for small parrots like finches, canaries, parakeets, and lovebirds — perfect for beak exercise and enrichment.',
 '<p>The <strong>HB01406 Small Parrot Pencil</strong> is a simple, yet effective enrichment toy made from safe natural wood, sized 10″ × 1″ and weighing 0.6 lb. Designed specifically for small avian companions — finches, canaries, parakeets, and lovebirds — this chew pencil encourages natural behaviors like gnawing, gripping, and climbing. Its lightweight design makes it easy to hang within any cage environment without adding bulk. The pencil format gives your pet a durable, safe outlet for beak exercise and mental stimulation. Ideal for small parrots needing a compact, reliable toy to promote activity and prevent boredom.</p>',
 'The HB01406 Small Parrot Pencil is a simple, yet effective enrichment toy made from safe natural wood, sized 10″ × 1″ and weighing 0.6 lb. Designed specifically for small avian companions — finches, canaries, parakeets, and lovebirds — this chew pencil encourages natural behaviors like gnawing, gripping, and climbing. Its lightweight design makes it easy to hang within any cage environment without adding bulk. The pencil format gives your pet a durable, safe outlet for beak exercise and mental stimulation. Ideal for small parrots needing a compact, reliable toy to promote activity and prevent boredom.'
),
(4,
 'ZVP‑4340 Smakers Vita Herbal Grandma’s Patch 2 pk',
 'aecageco.com',
 '<ul><li>Two herbal patch blocks designed for small birds to chew and nibble</li><li>Blended with natural herbs and grains for digestive and health benefits</li><li>Compact format—easy to mount inside cages</li><li>Encourages natural foraging and reduces boredom</li><li>Non‑toxic, bird‑safe formulation</li></ul>',
 '• Two herbal patch blocks designed for small birds to chew and nibble\n• Blended with natural herbs and grains for digestive and health benefits\n• Compact format—easy to mount inside cages\n• Encourages natural foraging and reduces boredom\n• Non‑toxic, bird‑safe formulation',
 '<ul><li>Contents: 2 herbal patches</li><li>Intended use: perch / chew / nibble supplement</li><li>Ingredients: natural herbs, grains, safe binding materials (bird‑grade)</li><li>Mounting: designed to attach to cage bars (slip‑in or clip style)</li><li>No artificial colors, dyes, or additives</li><li>Promotes beak activity, digestion, mental engagement</li></ul>',
 '• Contents: 2 herbal patches\n• Intended use: perch / chew / nibble supplement\n• Ingredients: natural herbs, grains, safe binding materials (bird‑grade)\n• Mounting: designed to attach to cage bars (slip‑in or clip style)\n• No artificial colors, dyes, or additives\n• Promotes beak activity, digestion, mental engagement',
 'Herbal chew patches to promote healthy foraging, digestion, and enrichment for small birds — delivered in a 2‑pack format.',
 'Herbal chew patches to promote healthy foraging, digestion, and enrichment for small birds — delivered in a 2‑pack format.',
 '<p>The <strong>ZVP‑4340 Smakers Vita Herbal Grandma’s Patch (2 pk)</strong> offers a natural chew and foraging treat designed to support small birds’ health and behavior. Each block combines safe bird‑grade herbs, grains, and binding material to encourage nibbling, chewing, and mental stimulation. The compact design fits easily into cages, allowing birds to peck, chew, and forage without taking up too much space. Free from artificial colors and additives, these patches help keep beaks active, reduce boredom, and contribute to digestive wellness. Perfect as a supplemental enrichment treat for finches, parakeets, lovebirds, and other small companion birds.</p>',
 'The ZVP‑4340 Smakers Vita Herbal Grandma’s Patch (2 pk) offers a natural chew and foraging treat designed to support small birds’ health and behavior. Each block combines safe bird‑grade herbs, grains, and binding material to encourage nibbling, chewing, and mental stimulation. The compact design fits easily into cages, allowing birds to peck, chew, and forage without taking up too much space. Free from artificial colors and additives, these patches help keep beaks active, reduce boredom, and contribute to digestive wellness. Perfect as a supplemental enrichment treat for finches, parakeets, lovebirds, and other small companion birds.'
),
(5,
 'NB146 Silly Straw Bundles Hanging Chew',
 'aecageco.com',
 '<ul><li>Multi‑material chew toy combining straw, wood, rattan & rope</li><li>Compact 7″ × 3″ design weighing just 0.035 lb</li><li>Hide treats inside for extra foraging fun</li><li>Easy to hang with included wooden C‑hook</li><li>Made from non‑toxic, bird‑safe materials to support dental health</li></ul>',
 '• Multi‑material chew toy combining straw, wood, rattan & rope\n• Compact 7″ × 3″ design weighing just 0.035 lb\n• Hide treats inside for extra foraging fun\n• Easy to hang with included wooden C‑hook\n• Made from non‑toxic, bird‑safe materials to support dental health',
 '<<ul><li>Dimensions: 7\" × 3\"</li><li>Weight: 0.035 lb</li><li>Materials: straw, wood, rattan, rope</li><li>Hanging method: wooden C hook</li><li>Foraging pockets: internal gaps to hide treats</li><li>Promotes chewing, mental play, and reduces anxiety</li><li>Tested for safety, non‑toxic materials</li><li>Suitable for small birds and small animals</li></ul>',
 '• Dimensions: 7" × 3"\n• Weight: 0.035 lb\n• Materials: straw, wood, rattan, rope\n• Hanging method: wooden C hook\n• Foraging pockets: internal gaps to hide treats\n• Promotes chewing, mental play, and reduces anxiety\n• Tested for safety, non‑toxic materials\n• Suitable for small birds and small animals',
 '<p>The <strong>NB146 Silly Straw Bundles Hanging Chew</strong> is a versatile enrichment toy crafted from a blend of straw, wood, rattan, and rope for maximum textural variety. Measuring 7″ × 3″ and weighing only 0.035 lb, it’s lightweight yet engaging. The design includes internal spaces to hide treats, turning every session into a mini foraging adventure. Equipped with a wooden C-hook, it mounts easily inside cages. Produced from non‑toxic materials and rigorously safety tested, this chew toy supports dental health, mental stimulation, and constructive chewing behavior in small birds and small animals. Ideal for adding environmental complexity and reducing cage boredom.</p>',
 'The NB146 Silly Straw Bundles Hanging Chew is a versatile enrichment toy crafted from a blend of straw, wood, rattan, and rope for maximum textural variety. Measuring 7″ × 3″ and weighing only 0.035 lb, it’s lightweight yet engaging. The design includes internal spaces to hide treats, turning every session into a mini foraging adventure. Equipped with a wooden C-hook, it mounts easily inside cages. Produced from non‑toxic materials and rigorously safety tested, this chew toy supports dental health, mental stimulation, and constructive chewing behavior in small birds and small animals. Ideal for adding environmental complexity and reducing cage boredom.'
),
(6,
 'MA2818FL HQ Platinum Elegant Flight Cage',
 'aecageco.com',
 '<ul><li>Elegant 28″ × 18″ × 54″ wrought iron cage with ½″ bar spacing and 2 mm wire thickness</li><li>Top opens with wood perch for play & out‑of‑cage access</li><li>Four feeder stations with stainless steel cups + one interior wood perch</li><li>Housing features include breeder box door, bottom shelf, and slide-out tray & grill</li><li>Mounted on four casters and includes a large front bird‑proof door with safety latch</li></ul>',
 '• Elegant 28″ × 18″ × 54″ wrought iron cage with ½″ bar spacing and 2 mm wire thickness\n• Top opens with wood perch for play & out‑of‑cage access\n• Four feeder stations with stainless steel cups + one interior wood perch\n• Housing features include breeder box door, bottom shelf, and slide-out tray & grill\n• Mounted on four casters and includes a large front bird‑proof door with safety latch',
 '<ul><li>Exterior dimensions: 28″ × 18″ × 54″</li><li>Interior height: 25″</li><li>Bar spacing: ½″; bar thickness: 2 mm</li><li>Material: wrought iron with non‑toxic powder coat</li><li>Front door: bird‑proof design with safety latch</li><li>Top: opens with wood perch</li><li>Feeder stations: 4 with stainless steel cups</li><li>Interior perch: 1 wood perch</li><li>Breeder box door</li><li>Bottom shelf: for storage</li><li>Slide-out tray & removable grill</li><li>Four rolling casters</li></ul>',
 '• Exterior dimensions: 28″ × 18″ × 54″\n• Interior height: 25″\n• Bar spacing: ½″; bar thickness: 2 mm\n• Material: wrought iron with non‑toxic powder coat\n• Front door: bird‑proof design with safety latch\n• Top: opens with wood perch\n• Feeder stations: 4 with stainless steel cups\n• Interior perch: 1 wood perch\n• Breeder box door\n• Bottom shelf: for storage\n• Slide-out tray & removable grill\n• Four rolling casters',
 'A refined, open-top flight cage featuring top access, ample feeders, slider cleaning tray, and full utility—designed for medium birds needing elegance and functionality.',
 'A refined, open-top flight cage featuring top access, ample feeders, slider cleaning tray, and full utility—designed for medium birds needing elegance and functionality.',
 '<p>The <strong>MA2818FL HQ Platinum Elegant Flight Cage</strong> delivers a blend of durability, utility, and style. With exterior dimensions of 28″ × 18″ × 54″ and an interior height of 25″, it offers ample room for medium birds to move and explore. Constructed of wrought iron with a safe, non‑toxic powder coat, the cage features ½″ bar spacing and 2 mm thick wire for strength and security.<br><br>A full-opening top with an integrated wood perch gives birds access to climb out or enjoy elevated vantage points. The front includes a bird-proof safety-latched door for convenient access. Inside, there are four feeder stations with stainless steel cups and a single wood perch for comfort. Additional features include a breeder box door for nesting, bottom shelf for storage, slide-out tray and grill for cleanliness, and mobility via four casters. Ideal for conures, cockatiels, small greys, and other similar-sized birds, this cage is both practical and visually appealing.</p>',
 'The MA2818FL HQ Platinum Elegant Flight Cage delivers a blend of durability, utility, and style. With exterior dimensions of 28″ × 18″ × 54″ and an interior height of 25″, it offers ample room for medium birds to move and explore. Constructed of wrought iron with a safe, non‑toxic powder coat, the cage features ½″ bar spacing and 2 mm thick wire for strength and security.  A full-opening top with an integrated wood perch gives birds access to climb out or enjoy elevated vantage points. The front includes a bird-proof safety-latched door for convenient access. Inside, there are four feeder stations with stainless steel cups and a single wood perch for comfort. Additional features include a breeder box door for nesting, bottom shelf for storage, slide-out tray and grill for cleanliness, and mobility via four casters. Ideal for conures, cockatiels, small greys, and other similar-sized birds, this cage is both practical and visually appealing.'
);


